
module.exports = {
    RESPONSECODE_OK :  0,
    RESPONSECODE_ERROR_NOT_CREATED : 101,
    RESPONSECODE_ERROR_PERSON_ALREADY_EXISTS : 111,
    RESPONSECODE_ERROR_PERSON_ALREADY_EXISTS_S : "Person already exists",
    RESPONSECODE_ERROR_RESOURCE_NOT_FOUND : 201,
    RESPONSECODE_ERROR_RESOURCE_NOT_FOUND_S : "Person not found",
    RESPONSECODE_ERROR_EMPTY_CONTENT : 301,
    RESPONSECODE_ERROR_EMPTY_CONTENT_S : "Content can not be empty!",
    RESPONSECODE_ERROR_MISSING_INPUT_DATA : 311,
    RESPONSECODE_ERROR_MISSING_INPUT_DATA_S : "Missing input data",
    RESPONSECODE_ERROR_GENERAL : 999,
};

